// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF4gqEQRF0oF_9naJncSnubyyGJo5lsAo',
    appId: '1:837968954360:web:c2d3154dfbc35f89150c0d',
    messagingSenderId: '837968954360',
    projectId: 'club-mana',
    authDomain: 'club-mana.firebaseapp.com',
    storageBucket: 'club-mana.firebasestorage.app',
    measurementId: 'G-K3LY1QBWJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sMwVDh97OVEJ8jywZkk9AwDrJJi3Xe0',
    appId: '1:837968954360:android:43ff26f92a8c3a9e150c0d',
    messagingSenderId: '837968954360',
    projectId: 'club-mana',
    storageBucket: 'club-mana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFGVOqKyDytqcVvUzsztA7lMRPH7glR5M',
    appId: '1:837968954360:ios:7f737585863869f0150c0d',
    messagingSenderId: '837968954360',
    projectId: 'club-mana',
    storageBucket: 'club-mana.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFGVOqKyDytqcVvUzsztA7lMRPH7glR5M',
    appId: '1:837968954360:ios:7f737585863869f0150c0d',
    messagingSenderId: '837968954360',
    projectId: 'club-mana',
    storageBucket: 'club-mana.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF4gqEQRF0oF_9naJncSnubyyGJo5lsAo',
    appId: '1:837968954360:web:52c4433d2d7c1e91150c0d',
    messagingSenderId: '837968954360',
    projectId: 'club-mana',
    authDomain: 'club-mana.firebaseapp.com',
    storageBucket: 'club-mana.firebasestorage.app',
    measurementId: 'G-K0PDHRW8F3',
  );

}